In [1]:
using  DelimitedFiles, Statistics, Random

In [2]:
data = download( "https://raw.githubusercontent.com/ilkerkesen/ufldl-tutorial/master/ex1/housing.data")

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49082  100 49082    0     0  45700      0  0:00:01  0:00:01 --:--:-- 45742


"/var/folders/ws/pgljpr_d6zldk3cx6b1640jr0000gn/T/juliaVg1oZy"

In [3]:
dt = readdlm(data)

506×14 Array{Float64,2}:
 0.00632  18.0   2.31  0.0  0.538  6.575  …  296.0  15.3  396.9    4.98  24.0
 0.02731   0.0   7.07  0.0  0.469  6.421     242.0  17.8  396.9    9.14  21.6
 0.02729   0.0   7.07  0.0  0.469  7.185     242.0  17.8  392.83   4.03  34.7
 0.03237   0.0   2.18  0.0  0.458  6.998     222.0  18.7  394.63   2.94  33.4
 0.06905   0.0   2.18  0.0  0.458  7.147     222.0  18.7  396.9    5.33  36.2
 0.02985   0.0   2.18  0.0  0.458  6.43   …  222.0  18.7  394.12   5.21  28.7
 0.08829  12.5   7.87  0.0  0.524  6.012     311.0  15.2  395.6   12.43  22.9
 0.14455  12.5   7.87  0.0  0.524  6.172     311.0  15.2  396.9   19.15  27.1
 0.21124  12.5   7.87  0.0  0.524  5.631     311.0  15.2  386.63  29.93  16.5
 0.17004  12.5   7.87  0.0  0.524  6.004     311.0  15.2  386.71  17.1   18.9
 0.22489  12.5   7.87  0.0  0.524  6.377  …  311.0  15.2  392.52  20.45  15.0
 0.11747  12.5   7.87  0.0  0.524  6.009     311.0  15.2  396.9   13.27  18.9
 0.09378  12.5   7.87  0.0  0.524  5.88

In [4]:
num_features = size(dt)[2]-1
num_instances = size(dt)[1]

506

In [5]:
x = transpose(dt[:,1:num_features])

13×506 LinearAlgebra.Transpose{Float64,Array{Float64,2}}:
   0.00632    0.02731    0.02729  …    0.06076    0.10959    0.04741
  18.0        0.0        0.0           0.0        0.0        0.0    
   2.31       7.07       7.07         11.93      11.93      11.93   
   0.0        0.0        0.0           0.0        0.0        0.0    
   0.538      0.469      0.469         0.573      0.573      0.573  
   6.575      6.421      7.185    …    6.976      6.794      6.03   
  65.2       78.9       61.1          91.0       89.3       80.8    
   4.09       4.9671     4.9671        2.1675     2.3889     2.505  
   1.0        2.0        2.0           1.0        1.0        1.0    
 296.0      242.0      242.0         273.0      273.0      273.0    
  15.3       17.8       17.8      …   21.0       21.0       21.0    
 396.9      396.9      392.83        396.9      393.45     396.9    
   4.98       9.14       4.03          5.64       6.48       7.88   

In [6]:
y = dt[:,num_features+1]

506-element Array{Float64,1}:
 24.0
 21.6
 34.7
 33.4
 36.2
 28.7
 22.9
 27.1
 16.5
 18.9
 15.0
 18.9
 21.7
  ⋮  
 24.5
 23.1
 19.7
 18.3
 21.2
 17.5
 16.8
 22.4
 20.6
 23.9
 22.0
 11.9

In [7]:
y = reshape(y,(1,num_instances))

1×506 Array{Float64,2}:
 24.0  21.6  34.7  33.4  36.2  28.7  …  16.8  22.4  20.6  23.9  22.0  11.9

In [8]:
x_normalized = (x .- mean(x, dims=2))./ std(x, dims=2)

13×506 Array{Float64,2}:
 -0.419367  -0.416927  -0.416929  …  -0.413038  -0.407361  -0.41459 
  0.284548  -0.48724   -0.48724      -0.48724   -0.48724   -0.48724 
 -1.28664   -0.592794  -0.592794      0.115624   0.115624   0.115624
 -0.272329  -0.272329  -0.272329     -0.272329  -0.272329  -0.272329
 -0.144075  -0.73953   -0.73953       0.157968   0.157968   0.157968
  0.413263   0.194082   1.28145   …   0.983986   0.724955  -0.362408
 -0.119895   0.366803  -0.265549      0.796661   0.736268   0.434302
  0.140075   0.556609   0.556609     -0.772919  -0.667776  -0.61264 
 -0.981871  -0.867024  -0.867024     -0.981871  -0.981871  -0.981871
 -0.665949  -0.986353  -0.986353     -0.802418  -0.802418  -0.802418
 -1.45756   -0.302794  -0.302794  …   1.1753     1.1753     1.1753  
  0.440616   0.440616   0.396035      0.440616   0.402826   0.440616
 -1.0745    -0.491953  -1.20753      -0.982076  -0.864446  -0.668397

In [9]:
using Random
Random.seed!(1)

MersenneTwister(UInt32[0x00000001], Random.DSFMT.DSFMT_state(Int32[1749029653, 1072851681, 1610647787, 1072862326, 1841712345, 1073426746, -198061126, 1073322060, -156153802, 1073567984  …  1977574422, 1073209915, 278919868, 1072835605, 1290372147, 18858467, 1815133874, -1716870370, 382, 0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], UInt128[0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000  …  0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x000000000000

In [10]:
permutation = randperm(num_instances)

506-element Array{Int64,1}:
 185
 311
 332
 340
 222
 171
 425
  21
 246
 226
 452
 404
 435
   ⋮
  25
 323
 351
 417
 139
 457
 301
 203
 414
 487
 298
 189

In [11]:
num_training = 400

400

In [12]:
xtrn = x_normalized[:,permutation[1:num_training]]
ytrn = y[:,permutation[1:num_training]]
xtst = x_normalized[:,permutation[num_training+1:num_instances]]
ytst = y[:,permutation[num_training+1:num_instances]]

1×106 Array{Float64,2}:
 20.3  27.5  22.0  30.7  19.4  24.5  …  24.8  42.3  16.3  19.1  20.3  29.8

In [13]:
weight = Any[0.1*randn(1,num_features)][1]

1×13 Array{Float64,2}:
 0.0426637  0.0378471  -0.169487  …  -0.0208622  -0.066244  -0.0257344

In [14]:
function predict(weight, x)
    return weight*x
end

predict (generic function with 1 method)

In [15]:
ypred = predict(weight, xtrn)

1×400 Array{Float64,2}:
 0.227025  -0.0623266  -0.0604358  …  0.207288  0.0592333  -0.0221864

In [16]:
function mse(weight, x, y)
    ypred = predict(weight, x)
    squared = (y - ypred).^2
    return sum(squared)/(2 * size(x)[2])
end

mse (generic function with 1 method)

In [17]:
print("(train loss/test loss): (", mse(weight,xtrn,ytrn)," ", mse(weight,xtst,ytst),")")

(train loss/test loss): (297.3036503276775 299.0172855668773)

In [18]:
function less_than_average(weight,x,y)
    ypred = predict(weight,x)
    avg = sqrt.(mse(weight,x,y))
    counter = 0 
    for i in 1:num_training
        if abs.(ypred[i]-y[i]) < avg
            counter += 1
        end
    end
    return counter
end

less_than_average (generic function with 1 method)

In [19]:
function less_than_average2(weight,x,y)
    ypred = predict(weight,x)
    avg = sqrt.(mse(weight,x,y))
    count(x -> (x < avg), (abs.(ypred-y)))
end

less_than_average2 (generic function with 1 method)

In [20]:
less_than_average2(weight, xtrn, ytrn)

108

In [21]:
### 17.03 Final version